// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package logic

import (
	_ "wiki/internal/logic/action"
	_ "wiki/internal/logic/case_step"
	_ "wiki/internal/logic/cases"
	_ "wiki/internal/logic/element"
	_ "wiki/internal/logic/page"
	_ "wiki/internal/logic/report"
	_ "wiki/internal/logic/step"
	_ "wiki/internal/logic/validator"
)
