// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Casereport is the golang structure of table casereport for DAO operations like Where/Data.
type Casereport struct {
	g.Meta   `orm:"table:casereport, do:true"`
	Id       interface{} //
	Message  interface{} //
	CaseId   interface{} //
	CaseDesc interface{} //
	RunTime  *gtime.Time //
	Status   interface{} //
	RunUser  interface{} //
	RunIp    interface{} //
}
