// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Cases is the golang structure of table cases for DAO operations like Where/Data.
type Cases struct {
	g.Meta      `orm:"table:cases, do:true"`
	Id          interface{} //
	ExecCount   interface{} //
	PassCount   interface{} //
	SkipCount   interface{} //
	FailedCount interface{} //
	HisId       interface{} //
	Description interface{} //
	OpenId      interface{} //
}
