// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Element is the golang structure of table element for DAO operations like Where/Data.
type Element struct {
	g.Meta      `orm:"table:element, do:true"`
	Id          interface{} //
	Name        interface{} //
	Description interface{} //
	PageId      interface{} //
	Path        interface{} //
	Attribute   interface{} //
	Father      interface{} //
}
