// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Page is the golang structure of table page for DAO operations like Where/Data.
type Page struct {
	g.Meta      `orm:"table:page, do:true"`
	Id          interface{} //
	Name        interface{} //
	Description interface{} //
	Url         interface{} //
}
