// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Step is the golang structure of table step for DAO operations like Where/Data.
type Step struct {
	g.Meta          `orm:"table:step, do:true"`
	Id              interface{} //
	Description     interface{} //
	TargetElementId interface{} //
	ActionId        interface{} //
	TargetPage      interface{} //
}
