// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// CaseStepDao is the data access object for table case_step.
type CaseStepDao struct {
	table   string          // table is the underlying table name of the DAO.
	group   string          // group is the database configuration group name of current DAO.
	columns CaseStepColumns // columns contains all the column names of Table for convenient usage.
}

// CaseStepColumns defines and stores column names for table case_step.
type CaseStepColumns struct {
	Id           string //
	StepId       string //
	Input        string //
	AssertExpect string //
	Description  string //
	CaseId       string //
	Score        string //
}

// caseStepColumns holds the columns for table case_step.
var caseStepColumns = CaseStepColumns{
	Id:           "id",
	StepId:       "step_id",
	Input:        "input",
	AssertExpect: "assert_expect",
	Description:  "description",
	CaseId:       "case_id",
	Score:        "score",
}

// NewCaseStepDao creates and returns a new DAO object for table data access.
func NewCaseStepDao() *CaseStepDao {
	return &CaseStepDao{
		group:   "default",
		table:   "case_step",
		columns: caseStepColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *CaseStepDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *CaseStepDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *CaseStepDao) Columns() CaseStepColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *CaseStepDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *CaseStepDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *CaseStepDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
