// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"wiki/internal/model"
	"wiki/internal/model/entity"
)

type (
	IElement interface {
		GetList(ctx context.Context, in model.ElementListInput) (out *model.ElementListOutput, err error)
		GetById(ctx context.Context, in uint64) (out *model.ElementOutput, err error)
		Create(ctx context.Context, in model.ElementCreateInput) (elementId int64, err error)
		Update(ctx context.Context, in *entity.Element) (err error)
		Delete(ctx context.Context, id int) (err error)
	}
)

var (
	localElement IElement
)

func Element() IElement {
	if localElement == nil {
		panic("implement not found for interface IElement, forgot register?")
	}
	return localElement
}

func RegisterElement(i IElement) {
	localElement = i
}
