// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package service

import (
	"context"
	"wiki/internal/model"
)

type IPage interface {
	GetList(ctx context.Context, in model.PageGetListInput) (out *model.PageGetListOutput, err error)
	GetById(ctx context.Context, in uint64) (out *model.PageOutputItem, err error)
	Create(ctx context.Context, in model.PageCreateInput) (out model.PageCreateOutput, err error)
	Update(ctx context.Context, in model.PageUpdateInput) (err error)
}

var localPage IPage

func Page() IPage {
	if localPage == nil {
		panic("implement not found for interface IPage, forgot register?")
	}
	return localPage
}

func RegisterPage(i IPage) {
	localPage = i
}
