// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"wiki/internal/model"
	"wiki/internal/model/entity"
)

type (
	IStep interface {
		GetList(ctx context.Context, in model.StepListInput) (out *model.StepListOutput, err error)
		GetById(ctx context.Context, in uint64) (out *model.StepOutput, err error)
		Create(ctx context.Context, in model.StepCreateInput) (stepId int64, err error)
		Update(ctx context.Context, in *entity.Step) (err error)
		Delete(ctx context.Context, id int) (err error)
	}
)

var (
	localStep IStep
)

func Step() IStep {
	if localStep == nil {
		panic("implement not found for interface IStep, forgot register?")
	}
	return localStep
}

func RegisterStep(i IStep) {
	localStep = i
}
