// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wiki/internal/dao/internal"
)

// internalCaseStepDao is internal type for wrapping internal DAO implements.
type internalCaseStepDao = *internal.CaseStepDao

// caseStepDao is the data access object for table case_step.
// You can define custom methods on it to extend its functionality as you wish.
type caseStepDao struct {
	internalCaseStepDao
}

var (
	// CaseStep is globally public accessible object for table case_step operations.
	CaseStep = caseStepDao{
		internal.NewCaseStepDao(),
	}
)

// Fill with you ideas below.
