// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wiki/internal/dao/internal"
)

// internalCasereportDao is internal type for wrapping internal DAO implements.
type internalCasereportDao = *internal.CasereportDao

// casereportDao is the data access object for table casereport.
// You can define custom methods on it to extend its functionality as you wish.
type casereportDao struct {
	internalCasereportDao
}

var (
	// Casereport is globally public accessible object for table casereport operations.
	Casereport = casereportDao{
		internal.NewCasereportDao(),
	}
)

// Fill with you ideas below.
