// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wiki/internal/dao/internal"
)

// internalCasesDao is internal type for wrapping internal DAO implements.
type internalCasesDao = *internal.CasesDao

// casesDao is the data access object for table cases.
// You can define custom methods on it to extend its functionality as you wish.
type casesDao struct {
	internalCasesDao
}

var (
	// Cases is globally public accessible object for table cases operations.
	Cases = casesDao{
		internal.NewCasesDao(),
	}
)

// Fill with you ideas below.
