// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wiki/internal/dao/internal"
)

// internalElementDao is internal type for wrapping internal DAO implements.
type internalElementDao = *internal.ElementDao

// elementDao is the data access object for table element.
// You can define custom methods on it to extend its functionality as you wish.
type elementDao struct {
	internalElementDao
}

var (
	// Element is globally public accessible object for table element operations.
	Element = elementDao{
		internal.NewElementDao(),
	}
)

// Fill with you ideas below.
