// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"wiki/internal/dao/internal"
)

// internalStepDao is internal type for wrapping internal DAO implements.
type internalStepDao = *internal.StepDao

// stepDao is the data access object for table step.
// You can define custom methods on it to extend its functionality as you wish.
type stepDao struct {
	internalStepDao
}

var (
	// Step is globally public accessible object for table step operations.
	Step = stepDao{
		internal.NewStepDao(),
	}
)

// Fill with you ideas below.
