// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CaseStep is the golang structure for table case_step.
type CaseStep struct {
	Id           int    `json:"id"           ` //
	StepId       int    `json:"stepId"       ` //
	Input        string `json:"input"        ` //
	AssertExpect string `json:"assertExpect" ` //
	Description  string `json:"description"  ` //
	CaseId       int    `json:"caseId"       ` //
	Score        int    `json:"score"        ` //
}
