// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Cases is the golang structure for table cases.
type Cases struct {
	Id          int    `json:"id"          ` //
	ExecCount   int    `json:"execCount"   ` //
	PassCount   int    `json:"passCount"   ` //
	SkipCount   int    `json:"skipCount"   ` //
	FailedCount int    `json:"failedCount" ` //
	HisId       string `json:"hisId"       ` //
	Description string `json:"description" ` //
	OpenId      int    `json:"openId"      ` //
}
