// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Element is the golang structure for table element.
type Element struct {
	Id          int    `json:"id"          ` //
	Name        string `json:"name"        ` //
	Description string `json:"description" ` //
	PageId      int    `json:"pageId"      ` //
	Path        string `json:"path"        ` //
	Attribute   string `json:"attribute"   ` //
	Father      int    `json:"father"      ` //
}
