// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Page is the golang structure for table page.
type Page struct {
	Id          int    `json:"id"          ` //
	Name        string `json:"name"        ` //
	Description string `json:"description" ` //
	Url         string `json:"url"         ` //
}
