// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// SqliteSequence is the golang structure for table sqlite_sequence.
type SqliteSequence struct {
	Name string `json:"name" ` //
	Seq  string `json:"seq"  ` //
}
