// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// Step is the golang structure for table step.
type Step struct {
	Id              int    `json:"id"              ` //
	Description     string `json:"description"     ` //
	TargetElementId int    `json:"targetElementId" ` //
	ActionId        int    `json:"actionId"        ` //
	TargetPage      int    `json:"targetPage"      ` //
}
